
import __ASTRO_IMAGE_IMPORT_b8R5s from "../../assets/portfolio/christham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F02-christham-net.json";
import __ASTRO_IMAGE_IMPORT_ZSC8QD from "../../assets/portfolio/hellotham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F03-hello-tham.json";
import __ASTRO_IMAGE_IMPORT_Z1ElHyX from "../../assets/portfolio/learning-jamstack.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F01-learning-jamstack.json";
import __ASTRO_IMAGE_IMPORT_Zczrzf from "../../assets/portfolio/my-chakra-components.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F07-my-chakra-components.json";
import __ASTRO_IMAGE_IMPORT_9rkNa from "../../assets/portfolio/my-record-collection.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F06-my-record-collection.json";
import __ASTRO_IMAGE_IMPORT_D6UX1 from "../../assets/portfolio/travel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F04-travels-through-a-lens.json";
import __ASTRO_IMAGE_IMPORT_Z1WdAoH from "../../assets/portfolio/visualvoyager.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F05-visual-voyager.json";
export default new Map([["../../assets/portfolio/christham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F02-christham-net.json", __ASTRO_IMAGE_IMPORT_b8R5s], ["../../assets/portfolio/hellotham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F03-hello-tham.json", __ASTRO_IMAGE_IMPORT_ZSC8QD], ["../../assets/portfolio/learning-jamstack.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F01-learning-jamstack.json", __ASTRO_IMAGE_IMPORT_Z1ElHyX], ["../../assets/portfolio/my-chakra-components.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F07-my-chakra-components.json", __ASTRO_IMAGE_IMPORT_Zczrzf], ["../../assets/portfolio/my-record-collection.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F06-my-record-collection.json", __ASTRO_IMAGE_IMPORT_9rkNa], ["../../assets/portfolio/travel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F04-travels-through-a-lens.json", __ASTRO_IMAGE_IMPORT_D6UX1], ["../../assets/portfolio/visualvoyager.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F05-visual-voyager.json", __ASTRO_IMAGE_IMPORT_Z1WdAoH]]);
		