
import __ASTRO_IMAGE_IMPORT_1N512O from "../../assets/portfolio/christham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F02-christham-net.md";
import __ASTRO_IMAGE_IMPORT_2cma2 from "../../assets/portfolio/hellotham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F03-hello-tham.md";
import __ASTRO_IMAGE_IMPORT_ZyjzkD from "../../assets/portfolio/learning-jamstack.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F01-learning-jamstack.md";
import __ASTRO_IMAGE_IMPORT_1bBskq from "../../assets/portfolio/my-chakra-components.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F07-my-chakra-components.md";
import __ASTRO_IMAGE_IMPORT_2hrGXL from "../../assets/portfolio/my-record-collection.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F06-my-record-collection.md";
import __ASTRO_IMAGE_IMPORT_RVI4G from "../../assets/portfolio/travel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F04-travels-through-a-lens.md";
import __ASTRO_IMAGE_IMPORT_9er60 from "../../assets/portfolio/visualvoyager.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F05-visual-voyager.md";
export default new Map([["../../assets/portfolio/christham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F02-christham-net.md", __ASTRO_IMAGE_IMPORT_1N512O], ["../../assets/portfolio/hellotham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F03-hello-tham.md", __ASTRO_IMAGE_IMPORT_2cma2], ["../../assets/portfolio/learning-jamstack.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F01-learning-jamstack.md", __ASTRO_IMAGE_IMPORT_ZyjzkD], ["../../assets/portfolio/my-chakra-components.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F07-my-chakra-components.md", __ASTRO_IMAGE_IMPORT_1bBskq], ["../../assets/portfolio/my-record-collection.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F06-my-record-collection.md", __ASTRO_IMAGE_IMPORT_2hrGXL], ["../../assets/portfolio/travel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F04-travels-through-a-lens.md", __ASTRO_IMAGE_IMPORT_RVI4G], ["../../assets/portfolio/visualvoyager.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2F05-visual-voyager.md", __ASTRO_IMAGE_IMPORT_9er60]]);
		