
import __ASTRO_IMAGE_IMPORT_ZqXxRY from "../../assets/portfolio/buddhavacana.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fbuddhavacana.md";
import __ASTRO_IMAGE_IMPORT_Ygip4 from "../../assets/portfolio/chris-tham-portfolio.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fchris-tham-portfolio.md";
import __ASTRO_IMAGE_IMPORT_ZVdxvJ from "../../assets/portfolio/chris-tham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fchris-tham.md";
import __ASTRO_IMAGE_IMPORT_2ig6nR from "../../assets/portfolio/hellotham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fhello-tham.md";
import __ASTRO_IMAGE_IMPORT_1vxX3M from "../../assets/portfolio/learning-jamstack.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Flearning-jamstack.md";
import __ASTRO_IMAGE_IMPORT_1aOhL4 from "../../assets/portfolio/my-chakra-components.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fmy-chakra-components.md";
import __ASTRO_IMAGE_IMPORT_1AEdMV from "../../assets/portfolio/my-record-collection.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fmy-record-collection.md";
import __ASTRO_IMAGE_IMPORT_ZQFENV from "../../assets/portfolio/rosely.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Frosely.md";
import __ASTRO_IMAGE_IMPORT_1lmf0c from "../../assets/portfolio/tidipa.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Ftidipa.md";
import __ASTRO_IMAGE_IMPORT_1Eyoh5 from "../../assets/portfolio/travel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Ftravels-through-a-lens.md";
import __ASTRO_IMAGE_IMPORT_ZrixU4 from "../../assets/portfolio/visualvoyager.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fvisual-voyager.md";
export default new Map([["../../assets/portfolio/buddhavacana.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fbuddhavacana.md", __ASTRO_IMAGE_IMPORT_ZqXxRY], ["../../assets/portfolio/chris-tham-portfolio.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fchris-tham-portfolio.md", __ASTRO_IMAGE_IMPORT_Ygip4], ["../../assets/portfolio/chris-tham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fchris-tham.md", __ASTRO_IMAGE_IMPORT_ZVdxvJ], ["../../assets/portfolio/hellotham.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fhello-tham.md", __ASTRO_IMAGE_IMPORT_2ig6nR], ["../../assets/portfolio/learning-jamstack.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Flearning-jamstack.md", __ASTRO_IMAGE_IMPORT_1vxX3M], ["../../assets/portfolio/my-chakra-components.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fmy-chakra-components.md", __ASTRO_IMAGE_IMPORT_1aOhL4], ["../../assets/portfolio/my-record-collection.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fmy-record-collection.md", __ASTRO_IMAGE_IMPORT_1AEdMV], ["../../assets/portfolio/rosely.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Frosely.md", __ASTRO_IMAGE_IMPORT_ZQFENV], ["../../assets/portfolio/tidipa.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Ftidipa.md", __ASTRO_IMAGE_IMPORT_1lmf0c], ["../../assets/portfolio/travel.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Ftravels-through-a-lens.md", __ASTRO_IMAGE_IMPORT_1Eyoh5], ["../../assets/portfolio/visualvoyager.jpg?astroContentImageFlag=&importer=src%2Fcontent%2FProjects%2Fvisual-voyager.md", __ASTRO_IMAGE_IMPORT_ZrixU4]]);
		