// Hero icons
export { default as MonitorIcon } from './monitor.svg'
export { default as HeadphoneIcon } from './headphones.svg'
export { default as HeartIcon } from './heart.svg'
export { default as MusicIcon } from './musicnote.svg'
export { default as CameraIcon } from './photo-camera.svg'
export { default as TurntableIcon } from './turntable.svg'
export { default as PortfolioIcon } from './portfolio.svg'
export { default as WebsiteIcon } from './website.svg'
export { default as PaletteIcon } from './paint-palette.svg'
export { default as HomeIcon } from './home.svg'
export { default as TravelIcon } from './travelling.svg'
export { default as BicycleIcon } from './bicycle.svg'
export { default as NotebookIcon } from './notebook.svg'
export { default as AustraliaIcon } from './australia.svg'
export { default as SydneyIcon } from './opera-house.svg'
export { default as KoalaIcon } from './koala.svg'
export { default as SpeakerIcon } from './speaker.svg'
export { default as PianoIcon } from './piano2.svg'
export { default as FloralIcon } from './floral-spring.svg'
export { default as GuitarIcon } from './guitar.svg'

// Projects icons
export { default as WrenchIcon } from './adjustable-wrench.svg'
export { default as RubikIcon } from './Rubik.svg'
export { default as BlueprintIcon } from './blueprint.svg'
export { default as AtomIcon } from './atom.svg'
export { default as PuzzleIcon } from './puzzle.svg'
export { default as CloudIcon } from './computing-cloud.svg'
export { default as FolderIcon } from './folders.svg'
export { default as GearsIcon } from './gears.svg'
export { default as GraphicsIcon } from './graphics.svg'
export { default as Notebook2Icon } from './notebook2.svg'
export { default as WorkflowIcon } from './workflow.svg'
export { default as CalculatorIcon } from './calculator.svg'
export { default as ChipIcon } from './chip.svg'
export { default as CompassIcon } from './compass.svg'
export { default as ProgrammingIcon } from './programming.svg'

// About icons
export { default as CoffeeIcon } from './coffee.svg'
export { default as ReadingIcon } from './reading.svg'
export { default as SunglassesIcon } from './sunglasses.svg'
export { default as WineIcon } from './wine.svg'
export { default as PhotoIcon } from './photo.svg'
export { default as BooksIcon } from './books.svg'
export { default as PawIcon } from './paw-print.svg'
export { default as DogIcon } from './dog.svg'
export { default as FlowerIcon } from './flower.svg'

// Contact icons
export { default as AgendaIcon } from './agenda.svg'
export { default as CheckListIcon } from './check-list.svg'
export { default as EmailIcon } from './email.svg'
export { default as PhoneIcon } from './smartphone.svg'
export { default as IDCardIcon } from './id-card.svg'
export { default as MapIcon } from './map.svg'
export { default as MessageIcon } from './message.svg'
export { default as SendIcon } from './send.svg'
export { default as PostItIcon } from './post-it.svg'
